import type { Metadata } from "next";
import { Space_Grotesk, Inter, Geist } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/components/web/ConvexClientProvider";
import { cn } from "@/lib/utils";
import Navbar from "@/components/web/Navbar";


const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-heading",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", spaceGrotesk.variable, inter.variable, "font-sans", geist.variable)}
    >
      <body className=" bg-[#0a0a0a] text-white min-h-full flex flex-col">
         <Navbar />
        <ConvexClientProvider>{children}</ConvexClientProvider></body>
    </html>
  );
}
